### ISSUE TITLE
[Bug] gpstop occured err 

### ISSUE THREAD

**Issue by fsmiledream** [cloudberrydb/cloudberrydb#665]
### Cloudberry Database version

1.6.0

### What happened

<img width="785" alt="gpstop-err" src="https://github.com/user-attachments/assets/d82bba68-5b16-4f36-88d3-b12b053f15e3">

### How to reproduce

maybe not incompatible ?

### Operating System

Kylin Linux Advanced Server V10 (Halberd)  -Kunpeng-920 aarch64

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by gongxun0928** [comment]
Check if the COORDINATOR_DATA_DIRECTORY environment variable is set
`env |grep COORDINATOR_DATA_DIRECTORY`

**Comment by yihong0618** [comment]
If you are using a demo for cloudberry you need two things in a new session

1. `source /xxxxxxxxxxxx/cloudberrydb/greenplum_path.sh`
2. `source /xxxxxxxx/cloudberrydb/gpAux/gpdemo/gpdemo-env.sh`

The env locate in teh gpdemo-env.sh
you can find them like:
```shell
export PGPORT=7000
export COORDINATOR_DATA_DIRECTORY=xxxxx
export MASTER_DATA_DIRECTORY=xxxxxxx
export NUM_PRIMARY_MIRROR_PAIRS=3
```
if you are using others instead of gpdemo, you can put them in `env` or `greenplum_path.sh`

and for the python code side, I think its better to make the error message more cleear.

**Comment by fsmiledream** [comment]
Thank you ！The err has been resolved.

**Comment by yihong0618** [comment]
My pleasure
