### ISSUE TITLE
Porting unique index for AO table to CBDB

### ISSUE THREAD

**Issue by my-ship-it** [cloudberrydb/cloudberrydb#68]

**Comment by lss602726449** [comment]
Still some bug in vacuum 
![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/7ce28114-dbab-4775-a61b-1dbf3349a500)

**Comment by lss602726449** [comment]
There is a bug in the test case introduced by GPDB

![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/cb5e938e-5231-49b7-b047-2a5b6c503e26)

Reason: Maybe get the wrong transaction  id  due to  gp_wait_until_triggered_fault 
wrong case : (gp_wait_until_triggered_fault first , then vacuum )


![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/6e8dfa0d-7185-4759-bdaa-3bbe35c11dbc)

right case:(vacuum first , then gp_wait_until_triggered_fault)


![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/ae045457-ee2a-4058-a369-2c20f00cd6e1)

FIX: Need Further study ( before call gp_wait_until_triggered_fault, sleep for a while  )

**Comment by lss602726449** [comment]
Another case in  fsync_ao.sql 


![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/dd95e347-d97e-439b-962c-603701c17882)


![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/0a016c33-5cb8-4f05-91ab-a2362680ce12)

Reason :
 1. Maybe the same way with previous one 
 2. Due to the asynchronization in the checkpoint

**Comment by lss602726449** [comment]
change the test case in sequential execution and pass the CI test


![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/f1844834-6935-4f41-b56c-2cd99d296a65)



![Image](https://github.com/cloudberrydb/cloudberrydb/assets/32217546/d53c453a-e739-41dd-bbfc-6121cb55800a)
